### ISSUE TITLE
OSDG Logo Fixes

### ISSUE THREAD

**Issue by ffledgling** [OSDG-IIITH/www#10]
- [x] Get rid of the misc lines that end up in the SVG version of the logo
- [x] Get rid of the text that says "Open Source Development Group"

**Comment by mrinaldhar** [comment]
Issue resolved. See #16

**Comment by ffledgling** [comment]
Not resolved till PR is merged :)

**Comment by mrinaldhar** [comment]
My bad. But now the PR has been merged. :P

**Comment by hharchani** [comment]
Why is this issue still open?

**Comment by mrinaldhar** [comment]
Done.
