### ISSUE TITLE
Add OSDG logo to top left of the website

### ISSUE THREAD

**Issue by ffledgling** [OSDG-IIITH/www#11]
Lose the opacity/alpha and add a solid version of the OSDG logo to the top left of the website.

**Comment by mrinaldhar** [comment]
Once I drop the text from the logo, like discussed, there would be no other place on the page where the full form of OSDG is mentioned. 

Do you want me to change the copyright from "(C) OSDG : IIIT-Hyderabad" to "(C) Open Source Developers Group (OSDG) : IIIT-Hyderabad"?

**Comment by ffledgling** [comment]
Nice catch, modifying the footer works great.

**Comment by mrinaldhar** [comment]
Issue resolved. See #16

**Comment by ffledgling** [comment]
Not resolved till PR is merged :)

**Comment by mrinaldhar** [comment]
Closing.
