### ISSUE TITLE
Paginate the existing website design

### ISSUE THREAD

**Issue by ffledgling** [OSDG-IIITH/www#13]
As it stands, all content for the website is in single page with AJAX for switching and loading.

Based on the IRC discussion (19-07-15), this has a few drawbacks
- Makes things harder to link
- Poorly done AJAX on slower internet connections is a bit of a nightmare, UX-wise.
- Pagination will make independent development of each section easier

For now, the general consensus is to switch to a proper page for each item in the nav bar.

**Comment by mrinaldhar** [comment]
Issue resolved. See #16

**Comment by ffledgling** [comment]
Not resolved till PR is merged :)

**Comment by mrinaldhar** [comment]
It’s safe to close this one now, I guess.
