### ISSUE TITLE
Experiment with reducing the text column's width

### ISSUE THREAD

**Issue by ffledgling** [OSDG-IIITH/www#14]
General consensus based on the IRC discussion (19-07-15), the text column is too wide.
It makes things a little hard to read, and the website a little overwhelming.

Current mitigation ideas are:
- Keep a single column, but experiment with different widths to see what works best.
- Have two columns, one for text, one for a 'Contact Us' or similar info-box.

Having a rough version of both so as to figure out what works would be great.

**Comment by ffledgling** [comment]
CC'ing @nisargjhaveri so he can keep an eye on this and give feedback.

**Comment by mrinaldhar** [comment]
See PR #16
