### ISSUE TITLE
Allow proper markup in stories. 

### ISSUE THREAD

**Issue by mrinaldhar** [OSDG-IIITH/www#17]

**Comment by polybuildr** [comment]
I wouldn't mind, actually. I'll take a look at the rest of the architecture at a nicer time and then look at a PHP markdown + PrismJS solution.

**Comment by polybuildr** [comment]
Ouch, this was supposed to be a reply to @amoghbl1's comment elsewhere.

**Comment by amoghbl1** [comment]
Right, I think they decided to move away from php and make it all html and js, now sure though! Speak to someone before looking into it...

**Comment by polybuildr** [comment]
Aha. That was something @nisargjhaveri wanted to do.

**Comment by amoghbl1** [comment]
@polybuildr wanna work on this then?? I'll add and assign you if you do!

**Comment by mrinaldhar** [comment]
@amoghbl1 We're still using PHP to do some really basic stuff (loading the header, footer, etc. using include statements). I don't have a particular affinity towards PHP, I did it out of habit. 

Thanks for taking up this issue, @polybuildr :D Fair warning, the rest of the code isn't cleaned up. I intended to do it once we were close to a release version.

**Comment by polybuildr** [comment]
@amoghbl1, I still haven't looked at it, so I'm not sure I'll be able to do it. I'll confirm in a few hours.

@mrinaldhar, don't worry, I'm used to working with messy code. :P I'll take a look and if I understand it, I'm up for this.

**Comment by amoghbl1** [comment]
@polybuildr Any update with this??

**Comment by polybuildr** [comment]
Unfortunately, no. I got dengue fever, so I was out of action for a week. I'll look at this soon.
