### ISSUE TITLE
Implement search for stories page

### ISSUE THREAD

**Issue by mrinaldhar** [OSDG-IIITH/www#19]

**Comment by mrinaldhar** [comment]
I had written something that took care of this a while ago. I'll clean it up and push.

**Comment by erilyth** [comment]
The search seems to not be working currently, When I try to search for a name it doesn't do anything. Has it been updated lately? (The search for authors etc)

**Comment by mrinaldhar** [comment]
The website hasn't been updated with that functionality. That's why this issue hasn't been closed yet.

**Comment by erilyth** [comment]
I tried to implement a simple search, is there anything else that must be modified or is it fine?

**Comment by mrinaldhar** [comment]
#38 by @erilyth resolves this.
