### ISSUE TITLE
Consider existing blogging tools

### ISSUE THREAD

**Issue by polybuildr** [OSDG-IIITH/www#27]
There are some great static blog generators out there like Jekyll or Pelican. There's also one I wrote, [Petroglyph](http://github.com/polybuildr/petroglyph). Are you sure you don't want to use any of these?

**Comment by ParthKolekar** [comment]
Existing blogging tools would be great. The Restructured Text functionality of 
[Petroglyph](http://github.com/polybuildr/petroglyph) would be handy here. 

@mrinaldhar Care for comments?

**Comment by mrinaldhar** [comment]
We _are_ going to use one of the existing blogging tools, for the OSDG blog. There was never any intention of writing a blogging platform from scratch for this, AFAIK.

**Comment by amoghbl1** [comment]
I guess they felt stories = blogs, not really! It's just supposed to be one static page so we didn't plan on having a whole blogging tool for it.
Closing this for now.
