### ISSUE TITLE
OSDG logo not displayed properly

### ISSUE THREAD

**Issue by nisargjhaveri** [OSDG-IIITH/www#4]
![screenshot](https://cloud.githubusercontent.com/assets/6381721/8764779/691ef5da-2e0b-11e5-99e4-8db14167a880.png)

**Comment by amoghbl1** [comment]
Can you give more details? What browser and screen res would definitely help!!

**Comment by nisargjhaveri** [comment]
Google Chrome 43 on Ubuntu 14.04
1286x1028 window size (reported by browser), 1366x768 (16:9) resolution. (I don't know how much it'll help though)

**Comment by nisargjhaveri** [comment]
This is because of the font that logo svg uses is not available. We should use png or other format rather than using svg directly.

**Comment by ffledgling** [comment]
Given that we're dropping the text entirely based on the IRC discussion ( Issue #10 ), can this be closed?

**Comment by mrinaldhar** [comment]
We've replaced the svg logo with a png one, so that solves this one. Closing.
